### part a
write down the design matrix X

In [59]:
# Use R for this question, but do not use the lm() function.
# Suppose (0, 1), (1, 3), (2, 5), (3, 6), (4, 5), (5, 7) are 6 independently observed data points, and a simple regression model (with intercept) is to be fit to these data.


# Write down the design matrix X.
X = matrix(c(0, 1, 1, 3, 2, 5, 3, 6, 4, 5, 5, 7), nrow = 6, ncol = 2, byrow = TRUE)
head(X)
n = nrow(X)
y <- X[, 2]
X <- X[, 1] # remove y

X1 <- rep(1, n)
X_design_matrix <- cbind(X1, X)
head(X_design_matrix)

[,1] [,2]
[1,] 0    1   
[2,] 1    3   
[3,] 2    5   
[4,] 3    6   
[5,] 4    5   
[6,] 5    7

X1 X
[1,] 1  0
[2,] 1  1
[3,] 1  2
[4,] 1  3
[5,] 1  4
[6,] 1  5

### Part b

determine the QR decomposition for X

In [60]:
# Determine the QR decomposition for X.
QR <- qr(X_design_matrix)
# QR

Q <- qr.Q(QR, complete = TRUE)
R <- qr.R(QR)
Q
R

[,1]       [,2]       [,3]        [,4]       [,5]       [,6]      
[1,] -0.4082483 -0.5976143 -0.39966534 -0.3614756 -0.3232858 -0.2850961
[2,] -0.4082483 -0.3585686 -0.06213786  0.1879790  0.4380958  0.6882127
[3,] -0.4082483 -0.1195229  0.88170280 -0.1180607 -0.1178243 -0.1175878
[4,] -0.4082483  0.1195229 -0.12913187  0.8228959 -0.2250764 -0.2730487
[5,] -0.4082483  0.3585686 -0.13996653 -0.2361476  0.6676714 -0.4285096
[6,] -0.4082483  0.5976143 -0.15080120 -0.2951910 -0.4395807  0.4160295

X1       X        
[1,] -2.44949 -6.123724
[2,]  0.00000  4.183300

# part c

Calculate inverse U

In [61]:
p <- 2  # number of columns in X -> 2
Q1 <- Q[, 1:p]
Q1
# y <- X[, 1] # 这里改成X的第二列是y
Q1y <- t(Q1)%*%y
U <- qr.R(QR)
inverse <- solve(U)
inverse


[,1]       [,2]      
[1,] -0.4082483 -0.5976143
[2,] -0.4082483 -0.3585686
[3,] -0.4082483 -0.1195229
[4,] -0.4082483  0.1195229
[5,] -0.4082483  0.3585686
[6,] -0.4082483  0.5976143

[,1]       [,2]      
X1 -0.4082483 -0.5976143
X   0.0000000  0.2390457

### part d 

slope and intercept estimate

In [62]:
betahat <- solve(U, Q1y)
betahat

[,1]    
X1 1.857143
X  1.057143

### part e

determine the residual sum of square

In [65]:
Q2 <- Q[, -(1:p)]
Q2
Q2y <- t(Q2)%*%y

SSE <- t(Q2y)%*%Q2y
SSE

[,1]        [,2]       [,3]       [,4]      
[1,] -0.39966534 -0.3614756 -0.3232858 -0.2850961
[2,] -0.06213786  0.1879790  0.4380958  0.6882127
[3,]  0.88170280 -0.1180607 -0.1178243 -0.1175878
[4,] -0.12913187  0.8228959 -0.2250764 -0.2730487
[5,] -0.13996653 -0.2361476  0.6676714 -0.4285096
[6,] -0.15080120 -0.2951910 -0.4395807  0.4160295

[,1]    
[1,] 3.942857

### part f

estimate the error variance

In [66]:
# estimate the error variance
MSE <- SSE/(n-p)
MSE

[,1]     
[1,] 0.9857143

### part g

calculate the test statistic used to determine whether the slope is 0 or not

In [82]:
# calculate the test statistic used to determine whether the slope is 0 or not


Uinv <- solve(U) # inverse of U 
U.diag <- diag(Uinv%*%t(Uinv)) # diag extracts the diagonal from a matrix 
T <- betahat/sqrt(sigma2hat * U.diag) 
T

ERROR: Error in eval(expr, envir, enclos): object 'sigma2hat' not found


In [80]:
x <- c(1, 1, 6, 1.5, 1, 6, 2, 60, 0)
x0 <- c(1, x)
x
x0
x0%*%betahat

[1]  1.0  1.0  6.0  1.5  1.0  6.0  2.0 60.0  0.0

[1]  1.0  1.0  1.0  6.0  1.5  1.0  6.0  2.0 60.0  0.0

ERROR: Error in x0 %*% betahat: non-conformable arguments
